services:
  # --- БРОКЕР СООБЩЕНИЙ KAFKA ---
  kafka:
    image: apache/kafka:3.7.0
    container_name: mes-kafka
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    healthcheck:
      # Используем более простую проверку доступности порта
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 10s       # Проверять каждые 10 сек
      timeout: 10s        # Ждать ответа 10 сек
      retries: 5          # 5 попыток
      start_period: 30s   # ПЕРВОЕ ПРАВИЛО: не трогать Кафку первые 30 секунд, она спит

  # --- ТВОЙ ПРИЛОЖЕНИЕ (MES GATEWAY) ---
  mes-gateway:
    build: .
    container_name: mes-gateway
    volumes:
      - ./src:/app/src  # <-- МАГИЯ ЗДЕСЬ: связываем папки
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=prod
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - API_KEY_SECRET=${API_KEY_SECRET}
      - DEBUG=True
    depends_on:
      kafka:
        condition: service_healthy # Ждем, пока Кафка реально будет готова

  # --- UI ДЛЯ КОНТРОЛЯ КАФКИ ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=factory-network
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

volumes:
  kafka_data:
    driver: local